Teresa/feature/adding products
Evgenios95/Frameworks-2022 pull request #6
Opened 2022-02-22 18:33 UTC by Saphala87

Hi guys, check out all the coffee we got. 

We focused on making the pictures 640x640 
- but some of them might need some retouching later on (with a real photo-editor) :)

2022-02-22 18:46 UTC, Saphala87 commented
Ready for review!

2022-02-27 17:41 UTC, Evgenios95 requested changes
Looks nice in general, please discuss the comments that I left :)

2022-02-27 17:41 UTC, Evgenios95 commented on mini-project-1/products.json
>      "discount": "nodiscount",
What about changing this k-v pair from `"discount": "nodiscount"` to: `onDiscount: false`.
When we have only 2 options, it's better to keep it simple and use a boolean instead.

2022-02-27 17:41 UTC, Evgenios95 commented on mini-project-1/products.json
> +    "category": ["Dark roast", "SML", "Starbucks"],
I don't think we have a reason to have an array here. We know for example that this is a Starbucks espresso. 
So this value  should be `"category": "Espresso"`.
Then, we can use the filter method provided by JS to display only the products that belong under this category.
Same with all the other objects: `"category": "Medium Roast"`

2022-02-27 17:41 UTC, Evgenios95 commented on mini-project-1/products.json
> +    "price": [59, 129],
For the sake of project 1, I suggest removing the array of prices and use a single price instead.
Let's consider doing that later in React. But this is not even needed in the project description.
We need to filter by something, that's why we have our categories.

2022-02-27 17:41 UTC, Evgenios95 commented on mini-project-1/products.json
> +    "category": ["Medium roast", "SL", "Starbucks"],
Remove the "SL" and all the other "SML". They are not a category.
Moreover there is a more elegant way to do it if we need to do it later.
We don't need to do that but consider some key value pairs like:

product_price: {
"S": 59,
"M": 79,
"L": 99,
}

2022-03-07 13:56 UTC, merged